name: Build ISO Image

on:
  push:
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare build environment
      run: |
       sudo apt update
       sudo apt install arch-install-scripts

    - name: Run builder
      run: sudo ./build.sh

    - name: List contents in ISO
      run: |
        du -m *.iso
        7z l *.iso

    - name: Upload ISO
      uses: actions/upload-artifact@v4
      with:
        name: iso
        compression-level: 0
        path: ./*.iso
